name: Test and deploy lambdas

on: [push, workflow_dispatch]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: test
        run: |
          pytest
        env:
          PG_HOST: ${{ secrets.TEST_PG_HOST }}
          PG_DB: ${{ secrets.TEST_PG_DB }}
          PG_PASSWORD: ${{ secrets.TEST_PG_PASSWORD }}
          PG_USER: ${{ secrets.TEST_PG_USER }}

  deploy:
    needs: test
    if: github.ref == 'refs/heads/main'
    strategy:
      matrix:
        lambda_name: ["traderBotOpen", "traderBotClosed", "traderAnalysis"]
        include:
          - lambda_name: "traderBotOpen"
            directory: "./botOpenLambda"
          - lambda_name: "traderBotClosed"
            directory: "./botClosedLambda"
          - lambda_name: "traderAnalysis"
            directory: "./analysisLambda"
            
    uses: ./.github/workflows/deploy_lambda.yml
    with:
        function_name: ${{ matrix.lambda_name }}
        function_dir: ${{ matrix.directory }}
    secrets: inherit
