name: Test and deploy lambdas

on: [push, workflow_dispatch]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: test
        run: |
          pytest

  deploy:
    needs: test
    if: github.ref == 'refs/heads/main'
    strategy:
      matrix:
        lambda_name: ["traderBotOpen"]
        include:
          - lambda_name: "traderBotOpen"
            directory: "./botOpenLambda"
            
    uses: ./.github/workflows/deploy_lambda.yml
    with:
        function_name: ${{ matrix.lambda_name }}
        function_dir: ${{ matrix.directory }}
    secrets: inherit
