name: Deploy lambda

# Controls when the workflow will run
on:
  workflow_call:
    inputs:
        function_name:
            required: true
            type: string
        function_dir:
            required: true
            type: string

jobs:
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
            python-version: '3.11'

      - name: install dependencies
        working-directory: ${{ inputs.function_dir }}
        run: "pip install -t src/vendor -r aws_requirements.txt --python-version 3.11"

      - name: zip
        working-directory: ${{ inputs.function_dir }}
        run: zip -r ../bundle.zip ./

      - name: default deploy
        uses: appleboy/lambda-action@v0.1.9
        with:
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws_region: ${{ secrets.AWS_REGION }}
          function_name: ${{ inputs.function_name }}
          zip_file: bundle.zip
